### ISSUE TITLE
support config option for rust-analyzer

### ISSUE THREAD

**Issue by fdncred** [sourcegear/rust-vs-extension#3]
I think I read that it uses rust-analyzer, which assumes it's in your path. In my case, it's not in my path. I think I have it working now by modifying my path to point to a folder where rust-analyzer already resides. It would be nice to provide a config option to set the location of rust-analyzer if it's not found automatically.

**Comment by ericsink** [comment]
Actually, we bundle a copy of the rust-analyzer executable in the extension and invoke it directly from there.  So it would seem that something else is going wrong.

But if modifying your path made things work, then the actual problem is something about what's in the path and what's not.  Like maybe rust-analyzer is invoking cargo with an assumption that it's in the path.  When our extension invokes cargo, it looks for it in the standard installed location.

**Comment by fdncred** [comment]
Thanks. I'll revert my change and play around some more. I didn't realize you were bundling rust-analyzer.

**Comment by ericsink** [comment]
FWIW, we consider our current bundling of rust-analyzer to be a temporary solution.  Once rustup supports rust-analyzer for stable toolchains, we would plan to use that.

And either way, we need config options for edge cases, alternate install locations, stuff not in the default path, etc.

**Comment by fdncred** [comment]
>  Once rustup supports rust-analyzer for stable ...

Ya, that makes sense.  Thanks for the info.

Totally love the debugging with this tool, although not perfect. Editing needs some work. I'm not making much head-way with out comments, better syntax highlighting, etc. But still, keep up the good work.

**Comment by ericsink** [comment]
I'm dogfooding the extension today on a Rust project and finding some annoyances too.  We've got plenty of testing and fixing to do.
